on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"

name: Release

jobs:
  release_workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}

      - name: Step 2 - Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.SONATYPE_USERNAME }} # env variable for username in deploy
          server-password: ${{ secrets.SONATYPE_PASSWORD }} # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # Value of the GPG private key to import
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # env variable for GPG private key passphrase

      - name: Step 3 - Configure Git user
        run: |
          git config --global user.name "release plugin"
          git config --global user.email "release-plugin@users.noreply.github.com"

      - name: Step 4 - Make Release
        run: |
          : # create release branch
          git checkout -b $RELEASE_BRANCH
          
          mvn versions:set -ntp -DnewVersion=${{ inputs.version }}
          
          git commit -m "Prepare release ${{ inputs.version }}"
          
          git tag -a $TAG
          
          : # merge to master all changes till release  
          git checkout master
          git merge $RELEASE_BRANCH
          
          : # merge to develop
          git checkout develop
          git merge $RELEASE_BRANCH
          
          : # create new snapshot version
          NEXT_VERSION="$(echo '${{ inputs.version }}' | perl -pe 's{^(([0-9]\.)+)?([0-9]+)$}{$1 . ($3 + 1) . "-SNAPSHOT"}e')"
          mvn versions:set -ntp -DnewVersion=$NEXT_VERSION
          
          :# alternatively:
          :# mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          :# NEXT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          git commit -m "Start next iteration with $NEXT_VERSION"
          
          : # push everything     
          git push --atomic origin $RELEASE_BRANCH master develop --follow-tags # all or nothing

        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          RELEASE_BRANCH: release-${{ github.event.inputs.version }}
          TAG: v${{ github.event.inputs.version }}

      - name: Step 5 - Deploy to Sonatype
        run: |
          git checkout master
          mvn clean deploy -ntp -DskipTests -U

      - name: Step 6 - Create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="$(git describe --abbrev=0)"
          echo $TAG
          gh release create "$TAG" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${TAG#v}" --generate-notes
